In [44]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (1.5.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pandas) (1.23.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2022.2.1)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Users\User\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [85]:
import pandas as pd


h_t = pd.read_csv('h.csv')
hh_t = pd.read_csv('hh.csv')
sa_t = pd.read_csv('sa.csv')

In [86]:
test = pd.merge(h_t, hh_t, on = ['자치구', '시점'], how = 'inner')
test = pd.merge(test, sa_t, on = ['자치구', '시점'], how = 'inner')
test.head()

,자치구,시점,단독주택,아파트,연립주택,다세대주택,비거주용건물내,총 합,단독주택 비율,아파트 비율,...,75~79세,80~84세,85세이상,전체인구수,청년층,청년층비율,중년층,중년층비율,노년층,노년층비율
0,종로구,2017,12920,14507,5451,11978,931,45787,0.282176,0.316837,...,998,608,430,23638,11474,0.485405,6441,0.272485,5723,0.242110
1,종로구,2018,12699,14530,5428,12140,932,45729,0.277701,0.317741,...,1014,674,444,25326,13013,0.513820,6449,0.254640,5864,0.231541
2,종로구,2019,12421,15290,5459,12349,921,46440,0.267463,0.329242,...,1047,704,470,24671,12209,0.494873,6348,0.257306,6114,0.247821
3,종로구,2020,12259,15688,5460,12540,912,46859,0.261615,0.334792,...,1108,749,547,25983,12744,0.490475,6615,0.254590,6624,0.254936
4,종로구,2021,11987,15775,5490,12725,908,46885,0.255668,0.336462,...,1133,811,597,27308,13347,0.488758,6850,0.250842,7111,0.260400

In [87]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 125 entries, 0 to 124
Data columns (total 50 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   자치구         125 non-null    object
 1   시점          125 non-null    int64
 2   단독주택        125 non-null    int64
 3   아파트         125 non-null    int64
 4   연립주택        125 non-null    int64
 5   다세대주택       125 non-null    int64
 6   비거주용건물내     125 non-null    int64
 7   총 합         125 non-null    int64
 8   단독주택 비율     125 non-null    float64
 9   아파트 비율      125 non-null    float64
 10  연립주택 비율     125 non-null    float64
 11  다세대주택 비율    125 non-null    float64
 12  비거주용건물내 비율  125 non-null    float64
 13  1인가구        125 non-null    int64
 14  2인가구        125 non-null    int64
 15  3인가구        125 non-null    int64
 16  4인가구        125 non-null    int64
 17  5인가구        125 non-null    int64
 18  6인가구        125 non-null    int64
 19  7인이상가구      125 non-null    int64
 20  총 가구수       125 non-null    int64
 21  1인가구 비율     125 non-null    float64
 22  2인가구 비율     125 non-null    float64
 23  3인가구 비율     125 non-null    float64
 24  4인가구 비율     125 non-null    float64
 25  5인가구 비율     125 non-null    float64
 26  6인가구 비율     125 non-null    float64
 27  7인가구이상 비율   125 non-null    float64
 28  20세미만       125 non-null    int64
 29  20~24세      125 non-null    int64
 30  25~29세      125 non-null    int64
 31  30~34세      125 non-null    int64
 32  35~39세      125 non-null    int64
 33  40~44세      125 non-null    int64
 34  45~49세      125 non-null    int64
 35  50~54세      125 non-null    int64
 36  55~59세      125 non-null    int64
 37  60~64세      125 non-null    int64
 38  65~69세      125 non-null    int64
 39  70~74세      125 non-null    int64
 40  75~79세      125 non-null    int64
 41  80~84세      125 non-null    int64
 42  85세이상       125 non-null    int64
 43  전체인구수       125 non-null    int64
 44  청년층         125 non-null    int64
 45  청년층비율       125 non-null    float64
 46  중년층         125 non-null    int64
 47  중년층비율       125 non-null    float64
 48  노년층         125 non-null    int64
 49  노년층비율       125 non-null    float64
dtypes: float64(15), int64(34), object(1)
memory usage: 49.8+ KB

In [88]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 125 entries, 0 to 124
Data columns (total 50 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   자치구         125 non-null    object
 1   시점          125 non-null    int64
 2   단독주택        125 non-null    int64
 3   아파트         125 non-null    int64
 4   연립주택        125 non-null    int64
 5   다세대주택       125 non-null    int64
 6   비거주용건물내     125 non-null    int64
 7   총 합         125 non-null    int64
 8   단독주택 비율     125 non-null    float64
 9   아파트 비율      125 non-null    float64
 10  연립주택 비율     125 non-null    float64
 11  다세대주택 비율    125 non-null    float64
 12  비거주용건물내 비율  125 non-null    float64
 13  1인가구        125 non-null    int64
 14  2인가구        125 non-null    int64
 15  3인가구        125 non-null    int64
 16  4인가구        125 non-null    int64
 17  5인가구        125 non-null    int64
 18  6인가구        125 non-null    int64
 19  7인이상가구      125 non-null    int64
 20  총 가구수       125 non-null    int64
 21  1인가구 비율     125 non-null    float64
 22  2인가구 비율     125 non-null    float64
 23  3인가구 비율     125 non-null    float64
 24  4인가구 비율     125 non-null    float64
 25  5인가구 비율     125 non-null    float64
 26  6인가구 비율     125 non-null    float64
 27  7인가구이상 비율   125 non-null    float64
 28  20세미만       125 non-null    int64
 29  20~24세      125 non-null    int64
 30  25~29세      125 non-null    int64
 31  30~34세      125 non-null    int64
 32  35~39세      125 non-null    int64
 33  40~44세      125 non-null    int64
 34  45~49세      125 non-null    int64
 35  50~54세      125 non-null    int64
 36  55~59세      125 non-null    int64
 37  60~64세      125 non-null    int64
 38  65~69세      125 non-null    int64
 39  70~74세      125 non-null    int64
 40  75~79세      125 non-null    int64
 41  80~84세      125 non-null    int64
 42  85세이상       125 non-null    int64
 43  전체인구수       125 non-null    int64
 44  청년층         125 non-null    int64
 45  청년층비율       125 non-null    float64
 46  중년층         125 non-null    int64
 47  중년층비율       125 non-null    float64
 48  노년층         125 non-null    int64
 49  노년층비율       125 non-null    float64
dtypes: float64(15), int64(34), object(1)
memory usage: 49.8+ KB

In [89]:
test = data.copy()
test = test[['자치구', '시점', '단독주택 비율', '아파트 비율', '연립주택 비율', '1인가구', '청년층', '중년층', '노년층']]
test.head()

   자치구    시점   단독주택 비율    아파트 비율   연립주택 비율   1인가구    청년층   중년층   노년층
0  종로구  2017  0.282176  0.316837  0.119051  23638  11474  6441  5723
1  종로구  2018  0.277701  0.317741  0.118699  25326  13013  6449  5864
2  종로구  2019  0.267463  0.329242  0.117550  24671  12209  6348  6114
3  종로구  2020  0.261615  0.334792  0.116520  25983  12744  6615  6624
4  종로구  2021  0.255668  0.336462  0.117095  27308  13347  6850  7111

In [90]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 125 entries, 0 to 124
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   자치구      125 non-null    object
 1   시점       125 non-null    int64
 2   단독주택 비율  125 non-null    float64
 3   아파트 비율   125 non-null    float64
 4   연립주택 비율  125 non-null    float64
 5   1인가구     125 non-null    int64
 6   청년층      125 non-null    int64
 7   중년층      125 non-null    int64
 8   노년층      125 non-null    int64
dtypes: float64(3), int64(5), object(1)
memory usage: 9.8+ KB

In [91]:
test1 = test.copy()

test1 = test1.loc[test1['시점'] == 2021]
test1.head(30)

      자치구    시점   단독주택 비율    아파트 비율   연립주택 비율    1인가구    청년층    중년층    노년층
4     종로구  2021  0.255668  0.336462  0.117095   27308  13347   6850   7111
9      중구  2021  0.138590  0.622108  0.044803   24544  11560   6242   6742
14    용산구  2021  0.181096  0.510054  0.051638   39270  19817  10347   9106
19    성동구  2021  0.108928  0.747971  0.021706   44946  22532  11327  11087
24    광진구  2021  0.165106  0.356232  0.045050   66140  38021  15157  12962
29   동대문구  2021  0.157143  0.637778  0.031519   65290  35548  13553  16189
34    중랑구  2021  0.157178  0.494820  0.038633   60487  21192  18531  20764
39    성북구  2021  0.154569  0.577766  0.044456   64985  34142  13779  17064
44    강북구  2021  0.176421  0.356449  0.049407   48428  15910  13738  18780
49    도봉구  2021  0.078261  0.604906  0.038913   37853  10713  11270  15870
54    노원구  2021  0.034426  0.864624  0.018093   60647  20526  15207  24914
59    은평구  2021  0.093338  0.412941  0.037279   62447  24742  16959  20746
64   서대문구  2021  0.121109  0.541353  0.053321   52792  29485  10781  12526
69    마포구  2021  0.088655  0.585977  0.024816   67162  40142  14789  12231
74    양천구  2021  0.052090  0.632721  0.027111   42973  14320  12306  16347
79    강서구  2021  0.050412  0.586126  0.023813   94436  47450  22254  24732
84    구로구  2021  0.084217  0.623970  0.055780   54980  23900  14845  16235
89    금천구  2021  0.121560  0.463954  0.055599   46827  22245  12490  12092
94   영등포구  2021  0.127305  0.702471  0.013597   69806  38611  16233  14962
99    동작구  2021  0.120150  0.545803  0.043578   68231  40703  13219  14309
104   관악구  2021  0.165194  0.434518  0.048629  136255  90470  24974  20811
109   서초구  2021  0.039402  0.705018  0.039106   45933  23043  12803  10087
114   강남구  2021  0.037029  0.731685  0.032671   71986  36821  19841  15324
119   송파구  2021  0.036114  0.609495  0.021879   79262  38734  21354  19174
124   강동구  2021  0.066611  0.651031  0.022031   56905  23276  15997  16569

In [92]:
test1.to_csv("test.csv", index = False)